package model

case class Rollercoaster(
                        id: String,
                        name: String,
                        park: String,
                        city: String,
                        province: String,
                        country: String,
                        status: String,
                        opening: Option[String],
                        closing: Option[String],
                        classification: Option[String],
                        rctype: Option[String],
                        scale: Option[String],
                        design: Option[String],
                        speed: Option[String],
                        inversions: Option[String],
                        elements: Option[List[String]],
                        trackLayout: Option[String],
                        tracklength: Option[String],
                        trackheight: Option[String],
                        category: Option[String],
                        restraints: Option[String],
                        )
